### ISSUE TITLE
Can this be changed to be applied to all xlink:href attr elements, or all <use> elements?

### ISSUE THREAD

**Issue by onlywei** [everdimension/angular-svg-base-fix#4]
Right now this is an attribute directive that must be manually applied onto a `<use>` tag. Do you think it makes sense to do:

`.directive('xlink:href', ...)`

or:

`.directive('use', { restrict: 'E' })`

instead?

@everdimension Is this safe? Have you thought about it in the past and decided against it for some reason?

**Comment by everdimension** [comment]
Hi! I did have a thought about this and consciously decided to use a specific attribute because I like when things are explicit. Having to write an extra attribute helps me remember that there's stuff being done besides native browser `svg` handling.

And the fact that this fix isn't needed when `html5Mode` is not enabled kind of made me want to make it explicit, too. Although it would make much more sense to gracefully shut down with a console notice if someone tries to use this directive without `html5Mode`.

I can't really think of anything else against your proposal.

I'll wait a little bit more for other people to express their opinion on this matter, but I'm fine with not using a custom attribute.

I'd prefer to use `.directive('xlink:href', ...)` definition, though. I think it's more appropriate.
